Repository hypertool/hypertool, pull requests merged in 2022-01, with the labels that each got.

#26 Update OAuth parameters
  packages/cli/source/auth/server.ts
  packages/cli/source/auth/session.ts
Labels: enhancement

#28 Update `deploy` command to deploy client
  packages/cli/source/compiler.ts
  packages/cli/source/index.ts
  packages/cli/source/manifest/client.ts
  packages/cli/source/utils/env.ts
  packages/cli/source/utils/fsHelper.ts
  packages/cli/source/utils/index.ts
Labels: enhancement

#30 Setup authentication package
  packages/authentication/.gitignore
  packages/authentication/package.json
  packages/authentication/source/index.ts
  packages/authentication/tsconfig.json
Labels: enhancement

#31 Setup authorization package
  packages/authorization/.gitignore
  packages/authorization/package.json
  packages/authorization/source/index.ts
  packages/authorization/tsconfig.json
Labels: enhancement

#32 Setup activity-logs package
  packages/activity-logs/.gitignore
  packages/activity-logs/package.json
  packages/activity-logs/source/index.ts
  packages/activity-logs/tsconfig.json
Labels: enhancement

#33 Write introductory docs for Hypertool
  docs/advantages-of-hypertool.md
  docs/introduction.md
  docs/problems-with-building-internal-tools.md
  docs/routing.md
  docs/why-not-drag-and-drop.md
Labels: documentation

#34 Setup tests for API
  .eslintrc.json
  lintstagedrc.json
  package.json
  packages/api/.eslintrc.json
  packages/api/.husky/pre-commit
  packages/api/.mocharc.json
  packages/api/.prettierignore
  packages/api/.prettierrc.json
  packages/api/.vscode/extensions.json
  packages/api/.vscode/settings.json
  packages/api/package.json
  packages/api/test/index.ts
  yarn.lock
Labels: enhancement

#38 Replaced invalid call to `disconnect()` with `stop()`
  packages/api/test/index.ts
Labels: bug

#39 Resolved `react-scripts` dependency issue
  packages/console/package.json
  yarn.lock
Labels: bug

#40 #HT-25: Create `ActivityLog` Mongoose model
  packages/api/source/models/ActivityLogModel.ts
  packages/api/source/models/index.ts
  packages/api/source/types/index.ts
  packages/api/source/utils/constants.ts
Labels: enhancement

#44 #HT-150: Setup preliminary scaffold
  packages/common/.mocharc.json
  packages/common/README.md
  packages/common/package.json
  packages/common/test/index.ts
  packages/common/tsconfig.json
  yarn.lock
Labels: enhancement

#45 #HT-25: Created tests for `ActivityLog` Mongoose model
  packages/api/package.json
  packages/api/source/models/ActivityLogModel.ts
  packages/api/test/helper/constants.ts
  packages/api/test/helper/index.ts
  packages/api/test/models/activityLog.test.ts
Labels: enhancement

#47 Move common symbols to `@hypertool/common`
  package.json
  packages/common/.gitignore
  packages/common/package.json
  packages/common/source/index.ts
  packages/common/source/models/ActivityLogModel.ts
  packages/common/source/models/AppModel.ts
  packages/common/source/models/GroupModel.ts
  packages/common/source/models/OrganizationModel.ts
  packages/common/source/models/QueryTemplateModel.ts
  packages/common/source/models/ResourceModel.ts
  packages/common/source/models/UserModel.ts
  packages/common/source/models/index.ts
  packages/common/source/types/index.ts
  packages/common/source/utils/constants.ts
  packages/common/source/utils/errors/BadRequestError.ts
  packages/common/source/utils/errors/NotFoundError.ts
  packages/common/source/utils/errors/UnauthorizedError.ts
  packages/common/source/utils/errors/index.ts
  packages/common/source/utils/google.ts
  packages/common/source/utils/index.ts
  packages/common/tsconfig.json
  yarn.lock
Labels: enhancement

#53 Setup tests for `@hypertool/authentication` package
  packages/authentication/package.json
  packages/authentication/test/index.ts
Labels: enhancement

#54 Setup tests for authorization
  packages/authorization/.mocharc.json
  packages/authorization/package.json
  packages/authorization/test/index.ts
  yarn.lock
Labels: enhancement

#55 HT-26: Create controllers to manage `ActivityLog`
  packages/api/package.json
  packages/api/source/controllers/ActivityLogController.ts
  packages/api/source/controllers/index.ts
  packages/api/source/graphql/privateAPI.ts
  packages/api/source/models/ActivityLogModel.ts
  packages/api/source/types/index.ts
  packages/api/source/utils/constants.ts
  packages/api/test/helper/constants.ts
  yarn.lock
Labels: enhancement

#57 Publish CLI v0.1.0
  lerna.json
  packages/cli/README.md
  packages/cli/bin/hypertool
  packages/cli/package.json
  packages/cli/source/auth/session.ts
  packages/cli/source/manifest/client.ts
  packages/cli/source/utils/paths.ts
  yarn.lock
Labels: enhancement

#56 HT-87: Port the query engine micro-service from Golang
  packages/query-engine/mocharc.json
  packages/query-engine/package.json
  packages/query-engine/source/app.ts
  packages/query-engine/source/controllers/index.ts
  packages/query-engine/source/controllers/query-engine-controller.ts
  packages/query-engine/source/rest/index.ts
  packages/query-engine/source/rest/query-engine-route.ts
  packages/query-engine/source/start.ts
  packages/query-engine/source/types/index.ts
  packages/query-engine/test/index.ts
Labels: enhancement

#59 HT-26: Added models, constants to `common` package
  packages/api/source/controllers/ActivityLogController.ts
  packages/api/source/graphql/privateAPI.ts
  packages/api/source/graphql/publicAPI.ts
  packages/common/source/types/index.ts
  packages/common/source/utils/constants.ts
Labels: enhancement

#69 HT-154: Updated `@hypertool/core` and `@hypertool/cli` to run applications
  packages/cli/package.json
  packages/cli/source/compiler.ts
  packages/cli/source/index.ts
  packages/cli/source/plugins/DefineHypertoolPlugin.ts
  packages/core/package.json
  packages/core/source/components/ApplicationRouter.tsx
  packages/core/source/components/Instantiate.tsx
  packages/core/source/screens/Error404.tsx
  packages/core/source/screens/index.ts
  yarn.lock
Labels: enhancement

#80 #HT-144: Update API Dockerfile
  packages/api/Dockerfile
  packages/api/package.json
  packages/query-engine/Dockerfile
Labels: enhancement

#74 HT-160: Update `create` command to install dependencies
  packages/cli/package.json
  packages/cli/source/index.ts
  packages/cli/source/project/index.ts
Labels: enhancement
